# Site settings
title: Stefan Zaun
email: stefan@stefanzaun.com
description: > # this means to ignore newlines until "baseurl:"
  Random Musings
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: twitter_username
github_username:  github_username

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"


#collections:
#  resume:
#    output: true
#    permalink: /resume/:path/
#  now:
#    output: true
#    permalink: /now/:path/